### ISSUE TITLE
Validation Toggle

### ISSUE THREAD

**Issue by MatthewVita** [MatthewVita/node-hl7-complete#7]
`node_hl7_complete.hl7.Parser.hl7ToXml` should take in a mandatory boolean parameter that tells the `HapiContext` to use validation or not. This will need to be passed in via JavaScript (the JavaScript boolean will be optional... defaults to true).

- https://sourceforge.net/p/hl7api/mailman/message/31244500/
- https://sourceforge.net/p/hl7api/mailman/message/33160852/

**Comment by MatthewVita** [comment]
...this will push the library to version 2.1.0 :)

**Comment by adamgoose** [comment]
Thank you, @MatthewVita!!! :D

**Comment by MatthewVita** [comment]
My pleasure. Please let me know if it tests well for your team!

**Comment by MatthewVita** [comment]
Hey @adamgoose, I just wanted to follow up on this. Is it testing well for your team?

Thanks,
Matthew
